import { ShiftOptimizeRequest, ShiftRequirement } from './types';

// デモ用居酒屋（15人×14日×3シフト）プリセットデータ
export const DEMO_IZAKAYA_DATA: ShiftOptimizeRequest = {
  period: {
    start_date: '2026-09-01',
    days: 14,
  },
  shifts: [
    {
      id: 'morning',
      name: '仕込み・ランチ',
      start: '10:00',
      end: '15:00',
      hours: 5.0,
      is_late_night: false,
    },
    {
      id: 'dinner',
      name: 'ディナーピーク',
      start: '17:00',
      end: '22:00',
      hours: 5.0,
      is_late_night: false,
    },
    {
      id: 'late_night',
      name: '深夜・締め作業',
      start: '21:30',
      end: '24:30',
      hours: 3.0,
      is_late_night: true,
    },
  ],
  staff_members: [
    {
      id: 'emp_01',
      name: '佐藤 店長 (社員)',
      is_minor: false,
      roles: ['kitchen_leader', 'hall'],
      hourly_wage: 1500,
      max_weekly_hours: 45.0,
      target_weekly_hours: 40.0,
      max_consecutive_days: 6,
    },
    {
      id: 'emp_02',
      name: '田中 副店長 (社員)',
      is_minor: false,
      roles: ['kitchen_leader', 'hall_leader'],
      hourly_wage: 1400,
      max_weekly_hours: 45.0,
      target_weekly_hours: 40.0,
      max_consecutive_days: 6,
    },
    {
      id: 'emp_03',
      name: '高橋 (フリーター/キッチン)',
      is_minor: false,
      roles: ['kitchen_leader'],
      hourly_wage: 1250,
      max_weekly_hours: 40.0,
      target_weekly_hours: 35.0,
      max_consecutive_days: 5,
    },
    {
      id: 'emp_04',
      name: '渡辺 (フリーター/ホール)',
      is_minor: false,
      roles: ['hall_leader', 'hall'],
      hourly_wage: 1200,
      max_weekly_hours: 35.0,
      target_weekly_hours: 30.0,
      max_consecutive_days: 5,
    },
    {
      id: 'emp_05',
      name: '伊藤 (大4/ホールリーダー)',
      is_minor: false,
      roles: ['hall_leader', 'hall'],
      hourly_wage: 1200,
      max_weekly_hours: 30.0,
      target_weekly_hours: 25.0,
      max_consecutive_days: 4,
    },
    {
      id: 'emp_06',
      name: '山本 (大3/キッチン)',
      is_minor: false,
      roles: ['kitchen'],
      hourly_wage: 1150,
      max_weekly_hours: 25.0,
      target_weekly_hours: 20.0,
      max_consecutive_days: 4,
    },
    {
      id: 'emp_07',
      name: '中村 (大3/ホール)',
      is_minor: false,
      roles: ['hall'],
      hourly_wage: 1150,
      max_weekly_hours: 25.0,
      target_weekly_hours: 20.0,
      max_consecutive_days: 4,
    },
    {
      id: 'emp_08',
      name: '小林 (大2/ホール)',
      is_minor: false,
      roles: ['hall'],
      hourly_wage: 1100,
      max_weekly_hours: 20.0,
      target_weekly_hours: 15.0,
      max_consecutive_days: 3,
    },
    {
      id: 'emp_09',
      name: '加藤 (大2/キッチン)',
      is_minor: false,
      roles: ['kitchen'],
      hourly_wage: 1100,
      max_weekly_hours: 20.0,
      target_weekly_hours: 15.0,
      max_consecutive_days: 3,
    },
    {
      id: 'emp_10',
      name: '吉田 (大1/ホール新人)',
      is_minor: false,
      roles: ['hall'],
      hourly_wage: 1100,
      max_weekly_hours: 15.0,
      target_weekly_hours: 12.0,
      max_consecutive_days: 3,
    },
    {
      id: 'emp_11',
      name: '山田 (大1/キッチン新人)',
      is_minor: false,
      roles: ['kitchen'],
      hourly_wage: 1100,
      max_weekly_hours: 15.0,
      target_weekly_hours: 12.0,
      max_consecutive_days: 3,
    },
    {
      id: 'emp_12',
      name: '佐々木 (主婦パート/昼)',
      is_minor: false,
      roles: ['kitchen', 'hall'],
      hourly_wage: 1150,
      max_weekly_hours: 20.0,
      target_weekly_hours: 15.0,
      max_consecutive_days: 4,
    },
    {
      id: 'emp_13',
      name: '松本 (主婦パート/昼)',
      is_minor: false,
      roles: ['kitchen'],
      hourly_wage: 1150,
      max_weekly_hours: 20.0,
      target_weekly_hours: 15.0,
      max_consecutive_days: 4,
    },
    {
      id: 'emp_14',
      name: '井上 (高校生/17歳)',
      is_minor: true, // 年少者: 深夜22時以降禁止
      roles: ['hall'],
      hourly_wage: 1050,
      max_weekly_hours: 15.0,
      target_weekly_hours: 10.0,
      max_consecutive_days: 3,
    },
    {
      id: 'emp_15',
      name: '木村 (高校生/16歳)',
      is_minor: true, // 年少者: 深夜22時以降禁止
      roles: ['hall'],
      hourly_wage: 1050,
      max_weekly_hours: 15.0,
      target_weekly_hours: 10.0,
      max_consecutive_days: 3,
    },
  ],
  requirements: Array.from({ length: 14 }, (_, day_offset): ShiftRequirement[] => [
    {
      day_offset,
      shift_id: 'morning',
      min_staff: 2,
      required_roles: { kitchen: 1 },
    },
    {
      day_offset,
      shift_id: 'dinner',
      min_staff: day_offset % 7 >= 4 ? 4 : 3, // 金土日は4名
      required_roles: { kitchen_leader: 1, hall: 1 },
    },
    {
      day_offset,
      shift_id: 'late_night',
      min_staff: 2,
      required_roles: {},
    },
  ]).flat(),
  availabilities: [
    // 高校生は深夜不可、ランチやディナー希望
    { staff_id: 'emp_14', day_offset: 0, shift_id: 'dinner', status: 'want' },
    { staff_id: 'emp_14', day_offset: 0, shift_id: 'late_night', status: 'unavailable' },
    { staff_id: 'emp_15', day_offset: 1, shift_id: 'dinner', status: 'want' },
    { staff_id: 'emp_15', day_offset: 1, shift_id: 'late_night', status: 'unavailable' },
    // 主婦パートはランチ希望
    { staff_id: 'emp_12', day_offset: 0, shift_id: 'morning', status: 'want' },
    { staff_id: 'emp_13', day_offset: 1, shift_id: 'morning', status: 'want' },
  ],
};
